from tkinter import  *
root =Tk()
root.geometry("400x550")
root.title("My Chatbot")
img=PhotoImage(file="D:/Haj/chatbot.png")
lblphoto=Label(root,image=img,bg="black",bd=3)
lblphoto.pack(pady=3)
frame=Frame(root)
sc=Scrollbar(frame)
chatbotx=Listbox(frame,width=60,height=10)
chatbotx.config(yscrollcommand=sc.set)
sc.config(command=chatbotx.yview)
sc.pack(side=RIGHT,fill=BOTH)
chatbotx.pack(side=LEFT,fill=BOTH,pady=10)
frame.pack()
user_input=Entry(root,font=("Arial",20))
user_input.pack(fill=BOTH)
btn=Button(root,bg="royalblue",fg="white",text="Ask To Bot",font=("Arial",20))
btn.pack(pady=10)
root.mainloop()